# Generated by Django 4.2.2 on 2023-06-20 02:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropostaEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=75, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('valor_emprestimo_solicitado', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('aprovado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
